### ISSUE TITLE
if multiple LOC find in MSCONS File, Converter can only output the last LOC as CSV

### ISSUE THREAD

**Issue by masterofdebian-dev** [vdmitriyev/msconsconverter#3]
Hallo Viktor,
[logfile-20240216-1036-da.log](https://github.com/vdmitriyev/msconsconverter/files/14309554/logfile-20240216-1036-da.log)
[MSCONS_TL_Multiple_LOC_SAMPLE.txt](https://github.com/vdmitriyev/msconsconverter/files/14309555/MSCONS_TL_Multiple_LOC_SAMPLE.txt)

if multiple LOC find in MSCONS File, Converter can only output the last LOC as CSV.

very kindly if you fix this.

In attachment you will find the sample MSCONS File and the Output Log.

Regards
Chen

**Comment by vdmitriyev** [comment]
@masterofdebian-dev thank you for reporting this error and providing test data. 
For now, I believe that the error was fixed. 
**Important***: Please note, that the CLI interface of the latest release was changed. For further details refer to the README.md

**Comment by vdmitriyev** [comment]
The bug was fixed in https://github.com/vdmitriyev/msconsconverter/commit/b5bd5d56681c1f87517ae763daccffb0614c01e6
